export const CHOSE_ANSWER = 'CHOSE_ANSWER';
export const REQUEST_QUESTIONS = 'REQUEST_QUESTIONS';
export const RECEIVE_QUESTIONS = 'RECEIVE_QUESTIONS';
export const SUBMIT_FOR_SOLUTIONS = 'SUBMIT_FOR_SOLUTIONS';

